
name: Node.js CI on Windows

on:
  push:
    branches:
      - main
      - dev
      - github-action-branch


jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js 18.17.1
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

